#!/usr/bin/env node
// Single source of truth for branding: `brand/<id>/brand.json` plus the
// approved assets next to it. This script projects one brand into every
// place the app reads it, so no name, identifier, colour, or icon is written
// by hand anywhere else:
//
//   src/renderer/generated/          brand.ts and app/tray icons
//   core/src/brand.rs                 Rust constants (tray, menus, data dir)
//   src-tauri/tauri.brand.conf.json   Tauri config overlay (ignored; passed as --config)
//   src-tauri/icons/                  legacy desktop icons and Icon Composer asset
//   assets/tray/trayTemplate*.png     monochrome template tray icon
//
// The default brand is `dstack`; `PRIVATE_AI_PROXY_BRAND=<id>` selects
// another. The renderer module, the Rust module, the desktop icons, and the
// tray icon are committed for the default brand and CI fails on drift; the
// Tauri overlay is regenerated on every run and merged by the CLI, so the
// tracked tauri.conf.json stays neutral. Required source assets and their
// recorded hashes are checked before generated files are written.
import { execFileSync } from "node:child_process";
import { appVersion, versionRelease } from "./release-channel.mjs";
import { distribution, MAC_APP_STORE_DISTRIBUTION, validateAppStoreBuildNumber } from "./distribution.mjs";
import { createHash } from "node:crypto";
import { copyFile, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { Resvg } from "@resvg/resvg-js";
import bmp from "bmp-js";
import sharp from "sharp";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const buildDistribution = distribution();
// Finder positions are icon centers. Keep the arrow and bundle configuration
// on the same coordinates; Tauri's pinned DMG template uses 128px icons.
const dmgLayout = {
  windowSize: { width: 660, height: 440 },
  appPosition: { x: 180, y: 230 },
  applicationFolderPosition: { x: 480, y: 230 },
};
const arrowX = (dmgLayout.appPosition.x + dmgLayout.applicationFolderPosition.x) / 2;
const arrowY = (dmgLayout.appPosition.y + dmgLayout.applicationFolderPosition.y) / 2;
const brandId = process.env.PRIVATE_AI_PROXY_BRAND ?? "dstack";
/** Cross-platform and legacy icon files listed alongside the native `.icon` asset. */
const LEGACY_DESKTOP_ICONS = ["32x32.png", "128x128.png", "128x128@2x.png", "icon.png", "icon.icns", "icon.ico"];
if (!/^[a-z][a-z0-9-]*$/.test(brandId)) {
  throw new Error(`PRIVATE_AI_PROXY_BRAND must be a lowercase id, got ${JSON.stringify(brandId)}`);
}
const brandDir = path.join(appRoot, "brand", brandId);
const brand = JSON.parse(await readFile(path.join(brandDir, "brand.json"), "utf8"));

const required = {
  id: "string",
  productName: "string",
  shortName: "string",
  organizationName: "string",
  byline: "string",
  tagline: "string",
  homepageUrl: "string",
  supportUrl: "string",
  supportEmail: "string",
  "service.name": "string",
  "service.defaultUrl": "string",
  "service.keyLabel": "string",
  "bundle.identifier": "string",
  "bundle.category": "string",
  "bundle.shortDescription": "string",
  "bundle.longDescription": "string",
  "theme.accentLight": "color",
  "theme.accentDark": "color",
  "theme.brandColor": "color",
  "theme.iconBackground": "color",
  "assets.appIconDefault": "file",
  "assets.appIconDark": "file",
  "assets.appIconComposer": "file",
  "assets.trayTemplate": "file",
  "assets.productWordmark": "file",
};
const problems = [];
for (const [key, kind] of Object.entries(required)) {
  const value = key.split(".").reduce((node, part) => node?.[part], brand);
  if (typeof value !== "string" || !value.trim()) {
    problems.push(`${key} is missing`);
  } else if (kind === "color" && !/^#[0-9a-f]{6}$/i.test(value)) {
    problems.push(`${key} must be a #rrggbb colour`);
  } else if (kind === "file" && !(await exists(path.join(brandDir, value)))) {
    problems.push(`${key} points at ${value}, which is not in ${brandDir}`);
  }
}
if (brand.id !== brandId) {
  problems.push(`brand.json id ${JSON.stringify(brand.id)} does not match directory ${brandId}`);
}
if (!/^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$/i.test(brand.bundle?.identifier ?? "")) {
  problems.push("bundle.identifier must be reverse-DNS");
}
for (const [file, digest] of Object.entries({ ...brand.source?.sha256, ...brand.iconSource?.sha256 })) {
  const actual = createHash("sha256").update(await readFile(path.join(brandDir, file))).digest("hex");
  if (actual !== digest) {
    problems.push(`${file} does not match its recorded sha256 (${actual})`);
  }
}
if (problems.length > 0) {
  throw new Error(`Brand ${brandId} is not buildable:\n  ${problems.join("\n  ")}`);
}

const asset = (name) => readFile(path.join(brandDir, brand.assets[name]), "utf8");
const generatedNote = `Generated by scripts/prepare-brand.mjs from brand/${brandId}/brand.json. Do not edit.`;
const appIconDefault = await readIcon("appIconDefault");
const appIconDark = await readIcon("appIconDark");
const composerSource = path.dirname(path.join(brandDir, brand.assets.appIconComposer));
const composer = JSON.parse(await readFile(path.join(brandDir, brand.assets.appIconComposer), "utf8"));
// Keep the author's document intact, and fail before generation if a referenced
// layer is missing. Icon Composer/actool owns material and appearance semantics.
for (const group of composer.groups) {
  for (const layer of group.layers) {
    if (layer["image-name"]) {
      await readFile(path.join(composerSource, "Assets", layer["image-name"]));
    }
  }
}
const traySource = await asset("trayTemplate");
const trayTemplateSvg = composeTrayTemplate(traySource);
// Preserve the exported artwork; only add the existing desktop canvas margin.
// PNG data URLs are used during offline rendering, never in the shipped UI.
const desktopIconSvg = pngIconSvg(appIconDefault[1024], 100);

// --- renderer -------------------------------------------------------------
// Renderer images are generated next to the module and imported as Vite assets,
// so they ship as self-hosted files under the production CSP (`img-src 'self'`,
// no `data:`).
const generatedDir = path.join(appRoot, "src/renderer/generated");
await mkdir(generatedDir, { recursive: true });
await writeFile(path.join(generatedDir, "app-icon-light.png"), appIconDefault[256]);
await writeFile(path.join(generatedDir, "app-icon-dark.png"), appIconDark[256]);
// Use vector wordmarks instead of system fonts so generated artwork is identical
// on Linux, Windows and macOS. Native installer/Finder labels remain accessible.
const wordmark = await asset("productWordmark");
const placeSvg = (svg, x, y, width, height) => {
  const size = svgSize(svg);
  return `<svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="0 0 ${size.width} ${size.height}">${inner(svg)}</svg>`;
};
const installerDir = path.join(appRoot, "src-tauri/installer");
await mkdir(installerDir, { recursive: true });
// Official NSIS bitmap sizes; retain Tauri's standard wizard and controls.
const installerArtwork = [
  ["header", 150, 57, `<rect width="150" height="57" fill="#ffffff"/>${placeSvg(pngIconSvg(appIconDefault[36]), 8, 10, 36, 36)}${placeSvg(wordmark, 50, 13, 95, 27)}`],
  ["sidebar", 164, 314, `
    <rect width="164" height="314" fill="#f3f6f2"/>
    ${placeSvg(pngIconSvg(appIconDefault[104]), 30, 56, 104, 104)}
    <rect x="0" y="248" width="164" height="66" fill="#f3f6f2"/>
    ${placeSvg(wordmark, 15, 262, 134, 38)}`],
];
for (const [name, width, height, content] of installerArtwork) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">${content}</svg>`;
  const pixels = new Resvg(svg).render().pixels;
  const data = Buffer.alloc(pixels.length);
  // resvg returns RGBA; bmp-js expects ABGR and encodes a 24-bit bitmap.
  for (let offset = 0; offset < pixels.length; offset += 4) {
    data[offset] = pixels[offset + 3];
    data[offset + 1] = pixels[offset + 2];
    data[offset + 2] = pixels[offset + 1];
    data[offset + 3] = pixels[offset];
  }
  await writeFile(path.join(installerDir, `brand-${name}.bmp`), bmp.encode({ data, width, height }).data);
}
// Leave the two drop targets and their Finder labels on a light, uncluttered
// surface. The arrow sits between the real icons, never baked-in stand-ins.
const dmgBackground = `<svg xmlns="http://www.w3.org/2000/svg" width="${dmgLayout.windowSize.width}" height="${dmgLayout.windowSize.height}">
  <rect width="100%" height="100%" fill="#f3f6f2"/>
  ${placeSvg(pngIconSvg(appIconDefault[54]), 44, 33, 54, 54)}
  ${placeSvg(wordmark, 114, 33, 206, 58)}
  <path d="M44 108H616" stroke="${brand.theme.iconBackground}" stroke-opacity=".10"/>
  <path d="M${arrowX - 30} ${arrowY}H${arrowX + 30}M${arrowX + 18} ${arrowY - 12}L${arrowX + 30} ${arrowY}L${arrowX + 18} ${arrowY + 12}" fill="none" stroke="${brand.theme.accentLight}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`;
await writeFile(path.join(installerDir, "brand-dmg-background.png"), render(dmgBackground, dmgLayout.windowSize.width));
await writeFile(path.join(generatedDir, "tray-mark.svg"), trayTemplateSvg);
const rendererBrand = {
  id: brand.id,
  productName: brand.productName,
  shortName: brand.shortName,
  organizationName: brand.organizationName,
  byline: brand.byline,
  tagline: brand.tagline,
  homepageUrl: brand.homepageUrl,
  supportUrl: brand.supportUrl,
  service: brand.service,
  theme: brand.theme,
};
await writeFile(
  path.join(generatedDir, "brand.ts"),
  `// ${generatedNote}
import appIconLight from "./app-icon-light.png";
import appIconDark from "./app-icon-dark.png";

export const brand = {
  ...${JSON.stringify(rendererBrand, null, 2).replace(/\n/g, "\n  ")},
  appIcon: { light: appIconLight, dark: appIconDark },
} as const;
`,
);

// --- Rust -----------------------------------------------------------------
const rust = (name, value) => {
  const prefix = `pub const ${name}: &str =`;
  const literal = `${JSON.stringify(value)};`;
  return `${prefix}${prefix.length + literal.length + 1 > 100 ? "\n    " : " "}${literal}`;
};
await writeFile(
  path.join(appRoot, "core/src/brand.rs"),
  `//! ${generatedNote}

${rust("ID", brand.id)}
${rust("PRODUCT_NAME", brand.productName)}
${rust("SHORT_NAME", brand.shortName)}
${rust("ORGANIZATION_NAME", brand.organizationName)}
${rust("BYLINE", brand.byline)}
${rust("TAGLINE", brand.tagline)}
${rust("HOMEPAGE_URL", brand.homepageUrl)}
${rust("SUPPORT_URL", brand.supportUrl)}
${rust("SERVICE_NAME", brand.service.name)}
${rust("SERVICE_DEFAULT_URL", brand.service.defaultUrl)}
/// Bundle identifier; names the per-user app data directory on every platform.
${rust("APP_IDENTIFIER", brand.bundle.identifier)}
`,
);

// --- Tauri config overlay ---------------------------------------------------
// Merged by `tauri dev|build --config` (RFC 7396: objects merge, arrays are
// replaced), and exported by the CLI as TAURI_CONFIG so the compiled context
// carries the same values. Only scalar product metadata goes here; the window
// list stays in the tracked config, and the window title is set at run time
// from the Rust brand module.
const appStoreBuildNumber = process.env.APPLE_APP_STORE_BUILD_NUMBER?.trim();
const updaterKey = process.env.TAURI_UPDATER_PUBLIC_KEY?.trim();
const updaterEndpoint = process.env.TAURI_UPDATER_ENDPOINT?.trim();
const windowsCertificateThumbprint = process.env.WINDOWS_CERTIFICATE_THUMBPRINT?.trim();
const nativeUpdater = Boolean(updaterKey);
if (buildDistribution === MAC_APP_STORE_DISTRIBUTION && (updaterKey || updaterEndpoint)) {
  throw new Error("Mac App Store builds cannot include the native updater");
}
if (appStoreBuildNumber && versionRelease(appVersion()).channel !== "stable") {
  throw new Error("Mac App Store releases must use a stable version");
}
if (buildDistribution !== MAC_APP_STORE_DISTRIBUTION && appStoreBuildNumber) {
  throw new Error("APPLE_APP_STORE_BUILD_NUMBER is only valid for Mac App Store builds");
}
if (appStoreBuildNumber) validateAppStoreBuildNumber(appStoreBuildNumber);
if (Boolean(updaterKey) !== Boolean(updaterEndpoint)) {
  throw new Error("Set both TAURI_UPDATER_PUBLIC_KEY and TAURI_UPDATER_ENDPOINT, or neither");
}
if (updaterEndpoint) {
  const release = versionRelease(appVersion());
  const endpoint = new URL(updaterEndpoint);
  if (!endpoint.pathname.endsWith(`/${release.feedTag}/latest.json`)) throw new Error("Updater endpoint does not match the release channel");
  if (endpoint.protocol !== "https:" || endpoint.username || endpoint.password) {
    throw new Error("The updater endpoint must use HTTPS without embedded credentials");
  }
}
if (windowsCertificateThumbprint && !/^[0-9a-f]{40}$/i.test(windowsCertificateThumbprint)) {
  throw new Error("WINDOWS_CERTIFICATE_THUMBPRINT must be a SHA-1 certificate thumbprint");
}
await writeFile(
  path.join(appRoot, "src-tauri/tauri.brand.conf.json"),
  `${JSON.stringify(
    {
      productName: brand.productName,
      identifier: brand.bundle.identifier,
      plugins: {
        "deep-link": { desktop: { schemes: [brand.bundle.identifier] } },
        ...(nativeUpdater ? { updater: { pubkey: updaterKey, endpoints: [updaterEndpoint] } } : {}),
      },
      bundle: {
        createUpdaterArtifacts: nativeUpdater,
        category: brand.bundle.category,
        shortDescription: brand.bundle.shortDescription,
        longDescription: brand.bundle.longDescription,
        publisher: brand.organizationName,
        homepage: brand.homepageUrl,
        macOS: {
          ...(appStoreBuildNumber ? { bundleVersion: appStoreBuildNumber } : {}),
          dmg: {
            background: "installer/brand-dmg-background.png",
            ...dmgLayout,
          },
        },
        windows: {
          ...(windowsCertificateThumbprint
            ? {
                certificateThumbprint: windowsCertificateThumbprint,
                digestAlgorithm: "sha256",
                timestampUrl: "http://timestamp.digicert.com",
              }
            : {}),
          nsis: {
            installerIcon: "icons/icon.ico",
            uninstallerIcon: "icons/icon.ico",
          },
        },
        ...(process.platform === "darwin"
          ? {
              icon: [...LEGACY_DESKTOP_ICONS.map((file) => `icons/${file}`), "icons/Assets.car"],
            }
          : {}),
      },
    },
    null,
    2,
  )}\n`,
);

// --- icons ------------------------------------------------------------------
// Project the complete hand-edited .icon package without regenerating its
// manifest or layers. macOS compiles the author's native appearance variants.
const composerDir = path.join(appRoot, "src-tauri/icons/AppIcon.icon");
await rm(composerDir, { recursive: true, force: true });
await cp(composerSource, composerDir, { recursive: true });

// Every static icon uses the Light export. Only native macOS appearances and
// the macOS renderer use the Dark artwork.
const scratch = path.join(appRoot, "brand/.generated");
await rm(scratch, { recursive: true, force: true });
await mkdir(scratch, { recursive: true });
try {
  const appIconPng = path.join(scratch, "app-icon.png");
  await writeFile(appIconPng, render(desktopIconSvg, 1024));
  const iconSet = path.join(scratch, "icons");
  execFileSync(process.execPath, [path.join(appRoot, "node_modules/@tauri-apps/cli/tauri.js"), "icon", appIconPng, "-o", iconSet], { stdio: "ignore" });
  for (const file of LEGACY_DESKTOP_ICONS) {
    const source = path.join(iconSet, file);
    const target = path.join(appRoot, "src-tauri/icons", file);
    if (file === "icon.icns") {
      // Tauri writes ICNS entries in hash order; sort for reproducibility.
      await writeFile(target, normalizeIcns(await readFile(source)));
    } else {
      await copyFile(source, target);
    }
  }

  // Menu bar: a monochrome template of the official mark (alpha only; macOS
  // tints it), never the coloured logo.
  const trayDir = path.join(appRoot, "assets/tray");
  await mkdir(trayDir, { recursive: true });
  await writeFile(path.join(trayDir, "trayTemplate.png"), render(trayTemplateSvg, 18));
  await writeFile(path.join(trayDir, "trayTemplate@2x.png"), render(trayTemplateSvg, 36));
} finally {
  await rm(scratch, { recursive: true, force: true });
}

console.log(`Prepared brand ${brandId}: ${brand.productName} (${brand.bundle.identifier})`);

// Icon Composer exports contain a Display P3 ICC profile. Convert colors to
// sRGB before any tool that discards profiles, and resize with a proper filter
// before embedding small icons in SVG installer artwork. Keep originals intact.
async function readIcon(name) {
  const input = sharp(path.join(brandDir, brand.assets[name])).withIccProfile("srgb", { attach: false });
  const sizes = [36, 54, 104, 256, 1024];
  return Object.fromEntries(await Promise.all(sizes.map(async (size) => [
    size, await input.clone().resize(size, size).png().toBuffer(),
  ])));
}

/** An ICNS file is a header plus (type, length, data) entries; order is free. */
function normalizeIcns(buffer) {
  if (buffer.toString("latin1", 0, 4) !== "icns") {
    throw new Error("tauri icon did not produce an icns file");
  }
  const entries = [];
  for (let offset = 8; offset < buffer.length; ) {
    const length = buffer.readUInt32BE(offset + 4);
    entries.push(buffer.subarray(offset, offset + length));
    offset += length;
  }
  entries.sort((a, b) => a.compare(b, 0, 4, 0, 4));
  return Buffer.concat([buffer.subarray(0, 8), ...entries]);
}

function pngIconSvg(png, inset = 0) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024"><image x="${inset}" y="${inset}" width="${1024 - 2 * inset}" height="${1024 - 2 * inset}" href="data:image/png;base64,${png.toString("base64")}"/></svg>`;
}

function render(svg, size) {
  return new Resvg(svg, { fitTo: { mode: "width", value: size } }).render().asPng();
}

function composeTrayTemplate(mark) {
  const { width, height } = svgSize(mark);
  // An 18pt menu-bar canvas with a 16pt mark, rendered at 1x and 2x.
  const scale = 16 / Math.max(width, height);
  const offsetX = 9 - (width * scale) / 2;
  const offsetY = 9 - (height * scale) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18"><svg x="${offsetX.toFixed(4)}" y="${offsetY.toFixed(4)}" width="${(width * scale).toFixed(4)}" height="${(height * scale).toFixed(4)}" viewBox="0 0 ${width} ${height}">${inner(mark)}</svg></svg>`;
}

function svgSize(svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]?.trim().split(/[\s,]+/).map(Number);
  if (viewBox?.length === 4) {
    return { width: viewBox[2], height: viewBox[3] };
  }
  const width = Number(svg.match(/\swidth="([\d.]+)"/)?.[1]);
  const height = Number(svg.match(/\sheight="([\d.]+)"/)?.[1]);
  if (!width || !height) {
    throw new Error("The app icon mark needs a viewBox or width/height");
  }
  return { width, height };
}

function inner(svg) {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  if (open < 0 || close < 0) {
    throw new Error("The app icon mark is not an SVG document");
  }
  return svg.slice(open + 1, close);
}

async function exists(file) {
  try {
    await readFile(file);
    return true;
  } catch {
    return false;
  }
}
